BASE_URL = "https://stellarburgers.education-services.ru/api"
REGISTER_URL = f"{BASE_URL}/auth/register"
ORDERS_URL = f"{BASE_URL}/orders"
LOGIN_URL = f"{BASE_URL}/auth/login"
AUTH_USER_URL = f"{BASE_URL}/auth/user"
INGREDIENTS_URL = f"{BASE_URL}/ingredients"
DELETE_USER_URL = f"{BASE_URL}/auth/user"